#!/bin/sh

#give tor 20 seconds to boostrap it self
sleep 20
echo '/#?<>' > /tmp/olddirsum

while true
do
	# docker and inotify/watch does not work very well with Windows. Polling is a proven concept
	ls -l -d /var/hs/ > /tmp/dirresult
	DIFF=$(diff /tmp/dirresult /tmp/olddirsum)
	
	if [ "$DIFF" != "" ] 
	then
		cp /tmp/dirresult /tmp/olddirsum
		echo "" > /tmp/hiddenservices.conf
		echo "" > /etc/tor/torrc

		rm -fR /var/hsdir/
		mkdir /var/hsdir/
		chmod -R 0700 /var/hsdir/

		for dir in $(ls -d /var/hs/*/ | xargs -n 1 basename); do
			mkdir /var/hsdir/$dir
			cp /var/hs/$dir/hostname /var/hsdir/$dir/hostname &> /dev/null
			cp /var/hs/$dir/private_key /var/hsdir/$dir/private_key &> /dev/null
		done

		for dir in $(ls -d /var/hs/*/ | xargs -n 1 basename); do
			echo "HiddenServiceDir /var/hsdir/$dir" >> /etc/tor/torrc
			echo "HiddenServicePort 80 127.0.0.1:8000" >> /etc/tor/torrc
		done

		chmod -R 0700 /var/hsdir/

		#create private_key and hostname
		killall -s HUP tor 
		# give tor some time to create files
		sleep 10

		for dir in $(ls -d /var/hs/*/ | xargs -n 1 basename); do
			cat /var/hs.tmpl >> /tmp/hiddenservices.conf
			echo "" >> /tmp/hiddenservices.conf
			sed -i "s|DIRNAME|/var/hs/$dir|g" /tmp/hiddenservices.conf
			sed -i "s|HOSTNAME|$(cat /var/hsdir/$dir/hostname)|g" /tmp/hiddenservices.conf
		done
		
		# copy back hostnames and private_key
		cp -u -R /var/hsdir/* /var/hs/
	
		#reload nginx
		killall -s HUP nginx

		#cat /etc/tor/torrc
		#cat /tmp/hiddenservices.conf

	fi
	sleep 10
done
echo "Exiting"